import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

/* Satoshi Font - Method 2: Next.js localFont with optimization */
const SATOSHI = localFont({
  src: "./Satoshi-Variable.ttf",
  variable: "--font-satoshi",
  display: "swap",
  fallback: ["Satoshi", "SF Pro", "system-ui", "arial"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${SATOSHI.variable} antialiased`}>{children}</body>
    </html>
  )
}
