substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: front-service
  _PROJECT_ID: payanywhere
  _ARTIFACT_REPO: front

steps:
  # 1. Generate .env file (for reference and debugging)
  - name: 'bash'
    id: CreateEnv
    entrypoint: bash
    dir: 'front'
    env:
      - NEXT_PUBLIC_ENVIRONMENT=${_NEXT_PUBLIC_ENVIRONMENT}
      - NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}
      - MP_PUBLIC_KEY=${_MP_PUBLIC_KEY}
      - MP_ACCESS_TOKEN=${_MP_ACCESS_TOKEN}
      - APP_ENV=${_APP_ENV}
    args:
      - -c
      - |
        echo "Creating .env file..."
        echo "APP_ENV=${_APP_ENV}" > .env
        echo "NEXT_PUBLIC_ENVIRONMENT=${_NEXT_PUBLIC_ENVIRONMENT}" >> .env
        echo "NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}" >> .env
        echo "NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}" >> .env
        echo "MP_PUBLIC_KEY=${_MP_PUBLIC_KEY}" >> .env
        echo "MP_ACCESS_TOKEN=${_MP_ACCESS_TOKEN}" >> .env
        echo ".env generated:"
        cat .env

  # 2. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'front'
    args: [
      'build',
      '--no-cache',
      '-t',
      '${_AR_HOSTNAME}/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_BACKEND_API_URL}',
      '--build-arg', 'NEXT_PUBLIC_ENVIRONMENT=${_APP_ENV}',
      '--build-arg', 'NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}',
      '--build-arg', 'MP_PUBLIC_KEY=${_MP_PUBLIC_KEY}',
      '--build-arg', 'MP_ACCESS_TOKEN=${_MP_ACCESS_TOKEN}',
      '.'
    ]

  # 3. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      '${_AR_HOSTNAME}/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
    ]

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_AR_HOSTNAME}/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
          NEXT_PUBLIC_API_URL=${_BACKEND_API_URL},
          NEXT_PUBLIC_ENVIRONMENT=${_APP_ENV},
          NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL},
          MP_PUBLIC_KEY=${_MP_PUBLIC_KEY},
          MP_ACCESS_TOKEN=${_MP_ACCESS_TOKEN}
      - '--project'
      - '${_PROJECT_ID}'

images:
  - '${_AR_HOSTNAME}/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
